### PR TITLE
Major refactoring: urlx.Parse(), u.Normalize(), u.Resolve()

### PR DESCRIPTION
**Pull request by VojtechVitek**

### CODE REVIEW

**Comment by pkieltyka** [comment]
MUCH better

**Comment by pkieltyka** [comment]
question: how come urlx.URL.String() implements its own string concatenation..? could it not just call url.String() from net/url that it embeds?

**Comment by pkieltyka** [comment]
I also think the name `Normalize()` sounds like a function that will mutate the underlying object, instead of returning a `NormalizedUrl()` string.. what do you think?

**Comment by VojtechVitek** [comment]
Changed the API according to @pkieltyka suggestions. Thanks for the feedback!

> I also think the name Normalize() sounds like a function that will mutate the underlying object, instead of returning a NormalizedUrl() string.. what do you think?
The Purell's functions returns only string, so we can't operate on URL struct level. And they're not willing to change the API. See pull request 12.

I'm going to merge this now. For additional feedback, please, create an issue.

**Pull request merged**
